version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - IRIS_MODEL_PATH=iris_model.pkl
      - NEWS_MODEL_PATH=news_model.pkl
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongodb/mongodb-community-server:7.0.4-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
